include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore

formatter:
  page_width: 120
  trailing_commas: preserve
